runtime: python39

entrypoint: streamlit run volley_app.py --server.port=$PORT --server.address=0.0.0.0

# Optional environment variables can be added here
# env_variables:
#   STREAMLIT_SERVER_ENABLECORS: "false"
#   STREAMLIT_SERVER_HEADLESS: "true"
